"""add_platform_and_intent_fields

Revision ID: 7aac17154ba7
Revises: 
Create Date: 2026-03-12 18:56:27.305523+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aac17154ba7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_pipelines', sa.Column('platform', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('source', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('intent_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'intent_data')
    op.drop_column('leads', 'source')
    op.drop_column('lead_pipelines', 'platform')
    # ### end Alembic commands ###
